apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    gcb-build-id: 5c462d35-a894-4b3a-8af5-737b3a266794
    gcb-trigger-id: c32e331b-9cb7-4e64-b3d6-9ef9d6998c38
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}","gcb-build-id":"5c462d35-a894-4b3a-8af5-737b3a266794","gcb-trigger-id":"c32e331b-9cb7-4e64-b3d6-9ef9d6998c38"},"creationTimestamp":"2022-02-11T09:23:21Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app":"core-container","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"core-container","app.kubernetes.io/version":"9074bc0215792159a18a379cde6d5d6a547f2351"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":8080,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:app":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"GoogleCloudConsole","operation":"Update","time":"2022-02-11T09:23:21Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:finalizers":{".":{},"v:\"service.kubernetes.io/load-balancer-cleanup\"":{}}},"f:status":{"f:loadBalancer":{"f:ingress":{}}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-02-11T09:23:55Z"}],"name":"core-container-service","namespace":"default","resourceVersion":"1553961","uid":"2d88a40f-3f77-492d-ab26-aaa457ecf1d9"},"spec":{"clusterIP":"10.56.10.103","clusterIPs":["10.56.10.103"],"externalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31154,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"core-container"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"34.136.163.180"}]}}}
  creationTimestamp: "2022-02-11T09:23:21Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: core-container
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: core-container
    app.kubernetes.io/version: 9074bc0215792159a18a379cde6d5d6a547f2351
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-02-11T09:23:21Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-02-11T09:23:55Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:gcb-build-id: {}
          f:gcb-trigger-id: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-02-11T09:37:05Z"
  name: core-container-service
  namespace: default
  resourceVersion: "1559060"
  uid: 2d88a40f-3f77-492d-ab26-aaa457ecf1d9
spec:
  clusterIP: 10.56.10.103
  clusterIPs:
  - 10.56.10.103
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31154
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: core-container
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.136.163.180
